### ISSUE TITLE
When setting multiple outputs with /51, no status is sent back

### ISSUE THREAD

**Issue by peoyli** [nielsonm236/NetMod-ServerApp#164]
http://192.168.1.4:8080/51FFFF0006
gives no output (after updating to 20230325 release)

**Comment by nielsonm236** [comment]
It's a bug resulting from my effort to start using two character hex instead of decimal inputs. All the input that were decimal before still work as they did before (ie, /55 is still /55, even if the "55" is now considered among a hex set of inputs).

But, I missed a code line with /51. I will fix and re-release.

Mike

**Comment by nielsonm236** [comment]
Addressed in release 20230328 0200
