### ISSUE TITLE
Changing output states over the REST interface

### ISSUE THREAD

**Issue by dom2049** [nielsonm236/NetMod-ServerApp#6]
Hi,

Changed my IP to 192.168.1.123 and trying to change states of one relay output. It changes fine when using your web interface, but when calling http://192.168.1.123:8080/00 and http://192.168.1.123:8080/01, your web IO status shows the change, but the relay doesn't change state? I have to click "Save" on the IO config page.

**Comment by nielsonm236** [comment]
I will retest this. If you use the REST commands you should see the relay output change immediately, but the IOControl page won't show the change until you click "Refresh". I will get back to you shortly. Can you tell me what revision shows on the Configuration page?

**Comment by dom2049** [comment]
It' showing Code Revision 20201126 1527.

**Comment by nielsonm236** [comment]
OK - That is the latest revision, and I just reproduced the problem. I will get to work on it right now.

**Comment by nielsonm236** [comment]
Just fixed it with release 20201128 1733. I will get this uploaded within the next few minutes. The issue was sourced by a recent change for MQTT support and the REST commands did not get re-tested after that. Fix was simple so it should not cause any other issues. Thank you for finding this. If you notice anything else let me know!
